#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$ROOT/build/coverage"
NIMCACHE_ROOT="$BUILD_DIR/nimcache"
GCOV_DIR="$BUILD_DIR/gcov"
SUMMARY="$BUILD_DIR/summary.txt"
SUMMARY_JSON="$BUILD_DIR/summary.json"

if ! command -v gcov >/dev/null 2>&1; then
  echo "gcov not found. Install GCC gcov to generate coverage." >&2
  exit 1
fi

rm -rf "$BUILD_DIR"
mkdir -p "$NIMCACHE_ROOT" "$GCOV_DIR"

COVERAGE_FLAGS=(
  --passC:-fprofile-arcs
  --passC:-ftest-coverage
  --passL:-fprofile-arcs
  --passL:-ftest-coverage
)

# Auto-discover tests to avoid having to update this list as new files are added.
# Keep discovery limited to the top level to preserve cache/output naming based on basename.
mapfile -t TESTS < <(
  cd "$ROOT"
  find tests/nim -maxdepth 1 -type f -name 'test_*.nim' -print | sort
)

if [[ ${#TESTS[@]} -eq 0 ]]; then
  echo "No Nim tests found at tests/nim/test_*.nim" >&2
  exit 1
fi

# Use a shared nimcache so modules are compiled once and reused across test binaries.
# This makes coverage runs dramatically faster while keeping per-test execution.
SHARED_CACHE_DIR="$NIMCACHE_ROOT/shared"
mkdir -p "$SHARED_CACHE_DIR"

MODE="${COVERAGE_MODE:-single}"

if [[ "$MODE" == "single" ]]; then
  RUNNER="$BUILD_DIR/all_tests_runner.nim"
  {
    echo "# Auto-generated by scripts/coverage_nim.sh"
    for test in "${TESTS[@]}"; do
      echo "import $(basename "$test" .nim)"
    done
  } >"$RUNNER"

  # Ensure the runner can import modules from tests/nim.
  nim c -r "${COVERAGE_FLAGS[@]}" --path:"$ROOT/tests/nim" --nimcache:"$SHARED_CACHE_DIR" "$RUNNER"
elif [[ "$MODE" == "multi" ]]; then
  for test in "${TESTS[@]}"; do
    nim c -r "${COVERAGE_FLAGS[@]}" --nimcache:"$SHARED_CACHE_DIR" "$ROOT/$test"
  done
else
  echo "Unknown COVERAGE_MODE='$MODE' (expected 'single' or 'multi')" >&2
  exit 2
fi

while IFS= read -r -d '' obj; do
  obj_dir="$(dirname "$obj")"
  (cd "$GCOV_DIR" && gcov -o "$obj_dir" "$obj" >/dev/null)
done < <(find "$SHARED_CACHE_DIR" -name '*.c.o' -print0)

python "$ROOT/scripts/coverage_summary.py" "$GCOV_DIR" "$ROOT" "$SUMMARY" "$SUMMARY_JSON"

echo "Coverage summary: $SUMMARY"
