#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$ROOT/build/coverage"
NIMCACHE_ROOT="$BUILD_DIR/nimcache"
GCOV_DIR="$BUILD_DIR/gcov"
SUMMARY="$BUILD_DIR/summary.txt"
SUMMARY_JSON="$BUILD_DIR/summary.json"

if ! command -v gcov >/dev/null 2>&1; then
  echo "gcov not found. Install GCC gcov to generate coverage." >&2
  exit 1
fi

rm -rf "$BUILD_DIR"
mkdir -p "$NIMCACHE_ROOT" "$GCOV_DIR"

COVERAGE_FLAGS=(
  --passC:-fprofile-arcs
  --passC:-ftest-coverage
  --passL:-fprofile-arcs
  --passL:-ftest-coverage
)

# Auto-discover tests to avoid having to update this list as new files are added.
# Keep discovery limited to the top level to preserve cache/output naming based on basename.
mapfile -t TESTS < <(
  cd "$ROOT"
  find tests/nim -maxdepth 1 -type f -name 'test_*.nim' -print | sort
)

if [[ ${#TESTS[@]} -eq 0 ]]; then
  echo "No Nim tests found at tests/nim/test_*.nim" >&2
  exit 1
fi

echo "Discovered ${#TESTS[@]} Nim tests"

# In single-binary mode we can safely use a shared nimcache.
# In multi-binary mode, sharing a nimcache can produce gcov checksum mismatches
# because the generated C/obj artifacts can differ per main module.
SHARED_CACHE_DIR="$NIMCACHE_ROOT/shared"
mkdir -p "$SHARED_CACHE_DIR"

MODE="${COVERAGE_MODE:-single}"
echo "Coverage mode: $MODE"

if [[ "$MODE" == "single" ]]; then
  RUNNER="$BUILD_DIR/all_tests_runner.nim"
  {
    echo "# Auto-generated by scripts/coverage_nim.sh"
    for test in "${TESTS[@]}"; do
      echo "import $(basename "$test" .nim)"
    done
  } >"$RUNNER"

  # Ensure the runner can import modules from tests/nim.
  nim c -r "${COVERAGE_FLAGS[@]}" --path:"$ROOT/tests/nim" --nimcache:"$SHARED_CACHE_DIR" "$RUNNER"

  while IFS= read -r -d '' obj; do
    obj_dir="$(dirname "$obj")"
    (cd "$GCOV_DIR" && gcov -o "$obj_dir" "$obj" >/dev/null)
  done < <(find "$SHARED_CACHE_DIR" -name '*.c.o' -print0)
elif [[ "$MODE" == "multi" ]]; then
  for test in "${TESTS[@]}"; do
    name="$(basename "$test" .nim)"
    cache_dir="$NIMCACHE_ROOT/$name"
    out_dir="$GCOV_DIR/$name"
    mkdir -p "$cache_dir" "$out_dir"
    nim c -r "${COVERAGE_FLAGS[@]}" --nimcache:"$cache_dir" "$ROOT/$test"
    while IFS= read -r -d '' obj; do
      obj_dir="$(dirname "$obj")"
      (cd "$out_dir" && gcov -o "$obj_dir" "$obj" >/dev/null)
    done < <(find "$cache_dir" -name '*.c.o' -print0)
  done
else
  echo "Unknown COVERAGE_MODE='$MODE' (expected 'single' or 'multi')" >&2
  exit 2
fi

python "$ROOT/scripts/coverage_summary.py" "$GCOV_DIR" "$ROOT" "$SUMMARY" "$SUMMARY_JSON"

echo "Coverage summary: $SUMMARY"
